export const experiences = [
  {
    id: 1,
    company: 'Resume.io',
    duration: 'May 2023 - Feb 2024',
    title: 'Senior Software Engineer',
    link: 'https://www.resume.io/',
    points: [
      'Spearheaded the development of resume templates and the resume builder for a product catering to 20 million registered users',
      'Implemented the Japanese Shokumukeirekisho template, attracting a user base of around 100,000',
      'Led the UI efforts for critical resume generation flows, including "Creating with AI" and "Creating with Examples," enhancing user experience and engagement',
      'Played a pivotal role in the internationalization (i18n) and localization of the website, ensuring seamless accessibility and user experience across 15+ countries.',
      'Implemented and concluded 10+ A/B tests, gaining data-driven insights to optimize features and increasing user satisfaction',
      'Developed numerous additional features, all with responsive web design, helping continuous improvement and evolution of the product',
    ],
  },
  {
    id: 2,
    company: 'Thriveworks',
    duration: 'May 2023 - Feb 2024',
    title: 'Senior Software Engineer',
    link: 'https://www.thriveworks.com/',
    points: [
      'Spearheaded the development of resume templates and the resume builder for a product catering to 20 million registered users',
      'Implemented the Japanese Shokumukeirekisho template, attracting a user base of around 100,000',
      'Led the UI efforts for critical resume generation flows, including "Creating with AI" and "Creating with Examples," enhancing user experience and engagement',
      'Played a pivotal role in the internationalization (i18n) and localization of the website, ensuring seamless accessibility and user experience across 15+ countries.',
      'Implemented and concluded 10+ A/B tests, gaining data-driven insights to optimize features and increasing user satisfaction',
      'Developed numerous additional features, all with responsive web design, helping continuous improvement and evolution of the product',
    ],
  },
  {
    id: 3,
    company: 'Kubernetes CD',
    duration: 'May 2023 - Feb 2024',
    title: 'Senior Software Engineer',
    points: [
      'Spearheaded the development of resume templates and the resume builder for a product catering to 20 million registered users',
      'Implemented the Japanese Shokumukeirekisho template, attracting a user base of around 100,000',
      'Led the UI efforts for critical resume generation flows, including "Creating with AI" and "Creating with Examples," enhancing user experience and engagement',
      'Played a pivotal role in the internationalization (i18n) and localization of the website, ensuring seamless accessibility and user experience across 15+ countries.',
      'Implemented and concluded 10+ A/B tests, gaining data-driven insights to optimize features and increasing user satisfaction',
      'Developed numerous additional features, all with responsive web design, helping continuous improvement and evolution of the product',
    ],
  },
  {
    id: 4,
    company: 'Levers Labs',
    duration: 'May 2023 - Feb 2024',
    title: 'Senior Software Engineer',
    points: [
      'Spearheaded the development of resume templates and the resume builder for a product catering to 20 million registered users',
      'Implemented the Japanese Shokumukeirekisho template, attracting a user base of around 100,000',
      'Led the UI efforts for critical resume generation flows, including "Creating with AI" and "Creating with Examples," enhancing user experience and engagement',
      'Played a pivotal role in the internationalization (i18n) and localization of the website, ensuring seamless accessibility and user experience across 15+ countries.',
      'Implemented and concluded 10+ A/B tests, gaining data-driven insights to optimize features and increasing user satisfaction',
      'Developed numerous additional features, all with responsive web design, helping continuous improvement and evolution of the product',
    ],
  },
];
